framework:
    messenger:
        # The bus that is going to be injected when injecting MessageBusInterface
        default_bus: command.bus
        buses:
            command.bus:
                middleware:
                    - doctrine_transaction
            query.bus:
            event.bus:
                default_middleware: allow_no_handlers
            message.bus:
                default_middleware: allow_no_handlers
#            external_message.bus: ~


        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # async: '%env(MESSENGER_TRANSPORT_DSN)%'
            # failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'
            external_messages:
                dsn: '%env(EXTERNAL_MESSAGE_TRANSPORT_DSN)%'
                serializer: App\Share\Infrastructure\Serializer\ExternalMessageSerializer
                retry_strategy:
                    max_retries: 3
                    # milliseconds delay
                    delay: 1000
                    # causes the delay to be higher before each retry
                    # e.g. 1 second delay, 2 seconds, 4 seconds
                    multiplier: 2
                    max_delay: 0
                options:
                    exchange:
                        name: delivery-calls-dashboard-DEV
                        type: topic
#                        default_publish_routing_key: '#'
                    queues:
                        service_dashboard_queue:
                            binding_keys: ['#']
#                            arguments:
#                                x-message-ttl: 1000
                    auto_setup: false
            external_messages_to_forward:
                dsn: '%env(EXTERNAL_MESSAGE_TRANSPORT_DSN)%'
                serializer: App\Share\Infrastructure\Serializer\ExternalMessageToForwardSerializer
                retry_strategy:
                    max_retries: 3
                    # milliseconds delay
                    delay: 1000
                    # causes the delay to be higher before each retry
                    # e.g. 1 second delay, 2 seconds, 4 seconds
                    multiplier: 2
                    max_delay: 0
                options:
                    exchange:
                        name: delivery-calls-dashboard-test-DEV
                        type: topic
                        default_publish_routing_key: '#'
                    queues:
                        service_dashboard_queue_test:
                            binding_keys: [ 'test' ]
                            arguments:
                                x-message-ttl: 30000 # 30 sec
                    auto_setup: true


#                        queues:
#                        messages_from_external:
#                            binding_keys: [ from_external ]
        routing:
            # Route your messages to the transports
            'App\Share\Infrastructure\Message\ExternalMessage': external_messages
            'App\Share\Infrastructure\Message\ExternalMessageToForward': external_messages_to_forward


# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
